services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: saugat-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - ml-service

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: saugat-backend
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/saugat
  #     - GOOGLE_API_KEY=${GOOGLE_API_KEY}
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ml-service:
    build:
      context: ./ml-service
    volumes:
      - ./ml-service:/app # Mount code so it auto-reloads
      - ./.env:/app/.env # Mount .env file
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  mongo_data: